services:
  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: TrendlyAI-Auth-Keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8090
      KC_HOSTNAME_URL: http://localhost:8090
    ports:
      - 8090:8090
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-db


  db:
    image: postgres:16
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - another_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  db-order:
    image: postgres:16
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



volumes:
  postgres_data:
  another_postgres_data:
  order_postgres_data:


